### ISSUE TITLE
Errors compiling on OpenBSD

### ISSUE THREAD

**Issue by Mjnd** [bsl/bindings-GLFW#14]
I'm unable to compile the bindings on OpenBSD, I modified bindings-GLFW.cabal "adding support" for OpenBSD with this change:
```
if os(linux) || os(freebsd) || os(openbsd)
```
When I try to compile these bindings I get this error:
```
$ runhaskell Setup.hs configure --user --extra-include-dir=/usr/X11R6/include/ --extra-lib-dir=/usr/X11R6/lib/
Configuring bindings-GLFW-3.0.3.3...
$ runhaskell Setup.hs build
Building bindings-GLFW-3.0.3.3...
Preprocessing library bindings-GLFW-3.0.3.3...
[1 of 1] Compiling Bindings.GLFW    ( dist/build/Bindings/GLFW.hs, dist/build/Bindings/GLFW.o ) [flags changed]
In file included from glfw/src/glx_platform.h:37,
                 from glfw/src/x11_platform.h:52,
                 from glfw/src/internal.h:69,
                 from glfw/src/x11_clipboard.c:27:0:
glfw/src/../deps/GL/glxext.h:275:0:
     error: redefinition of typedef 'GLXContextID'
/usr/X11R6/include/GL/glx.h:171:0:
     error: previous declaration of 'GLXContextID' was here
In file included from glfw/src/x11_platform.h:52,
                 from glfw/src/internal.h:69,
                 from glfw/src/x11_clipboard.c:27:0:
glfw/src/glx_platform.h:95:0:
     error: expected specifier-qualifier-list before 'pthread_key_t'
```
I used ghc 7.6.3p1, bindings-GLFW 3.0.3.3, glfw 3.0.4, OpenBSD 5.6.

**Comment by schell** [comment]
bindings-GLFW 3.0.3 includes glfw 3.0.3. I'm not sure if glfw 3.0.4 is causing a conflict (I would guess not). It's more likely that the included glfw needs to be configured for OpenBSD.

**Comment by schell** [comment]
@Mjnd - Can you try this again with the newest version of the bindings on hackage?

**Comment by Mjnd** [comment]
It works! Really thank you very much!
But if I try to build GLFW-b I get this error:

    Preprocessing library GLFW-b-1.4.7...
    [1 of 3] Compiling Graphics.UI.GLFW.Types ( Graphics/UI/GLFW/Types.hs,
    dist/build/Graphics/UI/GLFW/Types.o )
    Loading package ghc-prim ... linking ... done.
    Loading package integer-gmp ... linking ... done.
    Loading package base ... linking ... done.
    Loading package bindings-DSL-1.0.22 ... linking ... done.
    Loading package bindings-GLFW-3.1 ... linking ... ghc:
    /usr/X11R6/lib/libXxf86vm.a: unknown symbol `XextFindDisplay'
    ghc: unable to load package `bindings-GLFW-3.1'

But I guess this is an OpenBSD problem with one of its libraries missing something (maybe too old?), I'll try again with the new release of OpenBSD in may.
