### ISSUE TITLE
Update to 3.1

### ISSUE THREAD

**Issue by bananu7** [bsl/bindings-GLFW#16]

**Comment by schell** [comment]
This is in the works :+1:

**Comment by bananu7** [comment]
@schell Oh well good to know. I've spent a few hours diffing the sources and outlining the plan for update

I've noticed that headers weren't updated for 3.0.4 though, I'll make another issue for that.

**Comment by schell** [comment]
I would love help! Thank you! Any and all contributions are welcome. What platform are you on?

**Comment by bananu7** [comment]
I'm on Windows 7 and 8.1, both running x64 Platform.

I didn't get too far. I diffed the sources, which made me discover the header discrepancy. Otherwise, 3.1 moves a lot of files around, and some files appear to disappear; I'm not sure if their functionality is gone or simply moved.

**Comment by lukexi** [comment]
Yo dudes,

I updated these to 3.1 for OS X here: https://github.com/lukexi/bindings-GLFW/
(I was hitting a crash with multi-monitors/Rift in 3.0.3/3.0.4 so I needed to do it)

I was able to build GLFW-b on top of that and it worked great (and fixed the crash too : D )

I made what looked like the right tweaks for Windows and Linux but I haven't tested them yet, so you can just use it as inspiration for now if you like : ).

Cheers

**Comment by schell** [comment]
Bad ass Luke! Thanks! I'll start a pull request for you.

**Comment by schell** [comment]
I've opened the pull request as #18. @bananu7 - do you mind checking out @lukexi's master branch to validate that it builds on Windows?

**Comment by bananu7** [comment]
Ah sure I'll get to it ASAP. The notification/e-mail drowned somehow.
