### ISSUE TITLE
Headers in the repository are still on 3.0.3 version

### ISSUE THREAD

**Issue by bananu7** [bsl/bindings-GLFW#17]
Despite the fact, that the sources are on 3.0.4

**Comment by schell** [comment]
This is interesting, as I diff'd glfw from 3.03 to 3.04 and added any changed sources to the repo. I'm not sure how this slipped through the cracks.

**Comment by bananu7** [comment]
Maybe you did that just on `src`? It showcased only one fix for me.

**Comment by schell** [comment]
This is fixed with updates for 3.1.
