### ISSUE TITLE
Support for additions in 3.1

### ISSUE THREAD

**Issue by schell** [bsl/bindings-GLFW#19]
These additions were added in 3.1 and they need to make it into the bindings:
- [x] Added GLFWcursor custom system cursor handle
- [x] Added glfwCreateCursor, glfwCreateStandardCursor, glfwDestroyCursor and glfwSetCursor for managing system cursor images
- [x] Added GLFWimage struct for passing 32-bit RGBA images
- [ ] Added monitor and adapter identifier access to native API
- [x] Added glfwSetDropCallback and GLFWdropfun for receiving dropped files
- [ ] Added glfwPostEmptyEvent for allowing secondary threads to cause glfwWaitEvents to return
- [ ] Added empty test program for verifying posting of empty events
- [ ] Added glfwSetCharModsCallback for receiving character events with modifiers
- [ ] Added glfwGetWindowFrameSize for retrieving the size of the frame around the client area of a window
- [ ] Added GLFW_AUTO_ICONIFY for controlling whether full screen windows automatically iconify (and restore the previous video mode) on focus loss
- [ ] Added GLFW_DONT_CARE for indicating that any value is acceptable
- [ ] Added GLFW_DOUBLEBUFFER for controlling whether to use double buffering
- [ ] Added GLFW_CONTEXT_RELEASE_BEHAVIOR and values GLFW_ANY_RELEASE_BEHAVIOR, GLFW_RELEASE_BEHAVIOR_FLUSH and GLFW_RELEASE_BEHAVIOR_NONE for GL_KHR_context_flush_control support
- [ ] Added GLFW_INCLUDE_ES31 for including the OpenGL ES 3.1 header
- [ ] Added GLFW_FLOATING for creating always-on-top windowed mode windows
- [ ] Added GLFW_FOCUSED window hint for controlling initial input focus

**Comment by schell** [comment]
Work is being tracked in the branch additions-3.1

**Comment by schell** [comment]
http://www.glfw.org/docs/latest/news.html#news_31

**Comment by Mokosha** [comment]
This is now being tracked in #44.
