### ISSUE TITLE
bindings-GLFW-3.1.1 does not compile

### ISSUE THREAD

**Issue by peti** [bsl/bindings-GLFW#25]
Citing from http://hydra.cryp.to/build/627294/log/raw:

    1 of 1] Compiling Bindings.GLFW    ( dist/build/Bindings/GLFW.hs, dist/build/Bindings/GLFW.o )

    In file included from glfw/src/internal.h:74:0:
        0,
                         from glfw/src/context.c:28:

    glfw/src/x11_platform.h:38:33:
         fatal error: X11/Xcursor/Xcursor.h: No such file or directory
         #include <X11/Xcursor/Xcursor.h>
                                         ^
    compilation terminated.

Deja vu?

**Comment by schell** [comment]
I am currently debugging on an Arch linux virtualbox VM and hope to have this and a few other bugs squashed today or tonight.

**Comment by peti** [comment]
What baffles me a little is that I sent you a pull request to fix that error a while ago.

**Comment by schell** [comment]
Yes, I'm confused as well. Are you installing from the git repo or from hackage?

**Comment by peti** [comment]
Hackage.

**Comment by schell** [comment]
I can successfully build and install from hackage on my arch linux vm. This problem may be nix specific. I'll see if I can get another nix user to recreate - or try to get a nix vm up and running.

**Comment by peti** [comment]
> This problem may be nix specific.

Yes, we have been through all of this before. That is why I submitted a patch to remedy this issue. The easiest way to get those build errors fixed is to make a new release to Hackage that contains my patches, i.e. the current `master` branch of this repository.

**Comment by schell** [comment]
Okay - you'll still run into bsl/GLFW-b#49 so I will push to hackage after I have solved that. Thank you for your patience.

**Comment by schell** [comment]
@peti I've pushed up a branch (broken-49) for both bindings-GLFW and GLFW-b. If you'd like to check them out and confirm that your program can create a window that would be great.

**Comment by schell** [comment]
@peti I've uploaded new versions of bindings-GLFW and GLFW-b to hackage.
