### ISSUE TITLE
Source revision version number is wrong

### ISSUE THREAD

**Issue by phaazon** [bsl/bindings-GLFW#29]
I think someone’s forgotten to update the version number [here](http://hackage.haskell.org/package/bindings-GLFW-3.1.1.3/docs/src/Bindings-GLFW.html#c%27GLFW_VERSION_REVISION). Shouldn’t it be `1`? The `glfw3.h` header file might need to get updated then?

**Comment by schell** [comment]
The current version of glfw included in bindings-GLFW is 3.1.0. You can see the various version definitions in the glfw3.h file at https://github.com/bsl/bindings-GLFW/blob/master/glfw/include/GLFW/glfw3.h#L238. The bindings-DSL package keeps this in sync by providing some neat macros which are used here https://github.com/bsl/bindings-GLFW/blob/master/Bindings/GLFW.hsc#L29. As far as I can tell everything is in order. The headers were updated along with the rest of the glfw source after the release of 3.1.

The bindings-GLFW version and the glfw version don't necessarily correlate 1:1. The current bindings-GLFW version (3.1.1.3) doesn't bind to glfw 3.1.1.3, it binds to glfw 3.1.0. Does that make sense?

**Comment by phaazon** [comment]
Yeah, so the problem is not from the haskell package, but from GLFW. The revision number should b **1** for 3.**1**.

**Comment by schell** [comment]
I *think* it's correct. 3 is major, 1 minor and revision is 0. As far as I know, the version of GLFW that bindings-GLFW binds to is 3.1.0, which is reflected by the bindings. You can check out the header source in question here (https://github.com/bsl/bindings-GLFW/blob/master/glfw/include/GLFW/glfw3.h#L238).

This will be updated if/when we update the glfw source to 3.1.1.

**Comment by phaazon** [comment]
Alright then. Any way I can help?

**Comment by schell** [comment]
Sure! There are two important things that need doing - updating the glfw source to 3.1.1 or updating the bindings and GLFW-b to support the new features added in 3.1. I've started on the latter (work is in additions-3.1 branch https://github.com/bsl/bindings-GLFW/tree/additions-3.1) and both have github issues. You can also submit a PR for any issues in GLFW-b if you like :)
