### ISSUE TITLE
glfw3native.h bindings

### ISSUE THREAD

**Issue by vagarenko** [bsl/bindings-GLFW#33]
Could you please make bindings for these functions http://www.glfw.org/docs/latest/group__native.html

**Comment by Mokosha** [comment]
These seem like they're implemented using the ExposeNative cabal flag.

**Comment by Mokosha** [comment]
OK, it looks like they're not fully implemented. Only the header file is in.

**Comment by Mokosha** [comment]
This was fixed by #44.
