### ISSUE TITLE
Submit to Stackage

### ISSUE THREAD

**Issue by sgraf812** [bsl/bindings-GLFW#35]
I'm relatively new to Stackage and the `stack` stack, so I don't know if this isn't feasible.

But having this library (and `GLFW-b` ofc) on Stackage would be great! 

P.S.: Any suggestions on how to include it in a stack build anyway? I.e. is there are way to still load selected packages from Hackage?

**Comment by sgraf812** [comment]
I went forward and submitted a [PR](https://github.com/fpco/stackage/pull/753), which hopefully should be enough. I hope you don't mind!

**Comment by schell** [comment]
Looks like it worked!
![stack build bindings-GLFW](https://www.dropbox.com/s/ejsmx28picke5rd/Screenshot%202015-08-17%2010.48.38.png?raw=1)
Thanks!
