### ISSUE TITLE
Package needs a new maintainer

### ISSUE THREAD

**Issue by schell** [bsl/bindings-GLFW#39]
Please make a comment here if you would like to take maintainership.

**Comment by JavierJF** [comment]
Hi there! I would like to take the maintainership of the project.

**Comment by schell** [comment]
Hi! I'll add you to the maintainers - what's your Hackage username?

**Comment by schell** [comment]
@bsl - can you please add @JavierJF as a collaborator on this repo, or give me admin control so I can add him?

**Comment by JavierJF** [comment]
@schell Thanks! My Hackage username is "javjarfer". Thanks you for your trust, I will try my best to maintain the quality of this project.

**Comment by bsl** [comment]
I made @JavierJF a collaborator on this repo, and added javjarfer to the maintainers on Hackage. Thanks.

**Comment by cloudhead** [comment]
I'd be willing to help, since I'm using it for a fairly long-term project and don't want to see it fall behind.

**Comment by schell** [comment]
@cloudhead if @bsl doesn't give you collaborator rights you can always clone + PR. I'll be around sporadically to review and merge, as well as @JavierJF.

**Comment by cloudhead** [comment]
Got them for this repo, but not GLFW-b. Cheers.

**Comment by cloudhead** [comment]
@JavierJF how do you want to coordinate? IRC? Slack?

**Comment by JavierJF** [comment]
@cloudhead Well I wouldn't mind to use Slack, it comes with certain advantages over IRC that could be useful. To follow the conversation, please talk directly to me by mail, instead of using this issue. Thanks you.
