### ISSUE TITLE
HUnit 1.3 support

### ISSUE THREAD

**Issue by bergmark** [bsl/bindings-GLFW#40]
The test-suite for this package has been disabled in stackage because of this outdated dependency. When a fix is published to hackage please send a PR to re-enable the tests to stackage (it's in the skipped-tests section) or ping me.

Thanks!

**Comment by RyanGlScott** [comment]
Now update it to [`HUnit-1.4`](http://hackage.haskell.org/package/HUnit-1.4.0.0) :P

**Comment by RyanGlScott** [comment]
Or rather, [`HUnit-1.5`](http://hackage.haskell.org/package/HUnit-1.5.0.0)
