### ISSUE TITLE
update glfw to 3.2.1

### ISSUE THREAD

**Issue by joe9** [bsl/bindings-GLFW#41]
Hello,

Thanks for your effort in maintaining the package.

The latest GLFW version is 3.2.1. Just want to check if there are any plans to upgrade the bindings.

Thanks

**Comment by cloudhead** [comment]
Hey, yes, this is the next thing on the roadmap.

**Comment by joe9** [comment]
Hello,

Just want to check if the bindings are generated? Is this something that anyone else can do?

Thanks

**Comment by cloudhead** [comment]
The bindings aren't generated, but it looks like 3.1.2 doesn't have any API changes, so it should be fairly easy to update the local copy of glfw to that version. I don't have time right now, but you could give it a go.

**Comment by joe9** [comment]
Thanks. Updated my local branch to the latest glfw source files, removed some erroring out functions and it compiles and the bug is fixed.

**Comment by joe9** [comment]
submitted pull request @cloudhead

**Comment by YellowOnion** [comment]
3.2 has vulkan support! would love to start experimenting with this.

**Comment by YellowOnion** [comment]
Actually looking at this again, are we talking about 3.2.1 or 3.1.2. maybe there's some confusion here.

**Comment by cloudhead** [comment]
I'm working on moving us to 3.2.1 now, which is the latest release. The bug that was brought up was fixed in 3.1.2 though, which is an old release.

**Comment by cloudhead** [comment]
You can track this here: https://github.com/bsl/bindings-GLFW/pull/44
