### ISSUE TITLE
OpenBSD support for bindings-GLFW

### ISSUE THREAD

**Issue by Mjnd** [bsl/bindings-GLFW#70]
Hello, here I am again bothering you all. Hope you are all well.
This time the issue is related to cabal-install v3+ (I use v3.4.0.0). Apparently the new `v2-install` command style is unable to understand how to install a local package, by default fetching the package via internet from the repository. To have bindings-GLFW working on OpenBSD, I modify the file `bindings-GLFW.cabal` to have the line containing `if os(linux) || os(freebsd)` in  `if os(linux) || os(freebsd) || os(openbsd)`. This works fine with `cabal v1-install`, which understands how to install local packages, but I can no longer use this trick with `cabal v2-install`. I want to use the new v2 style because the v1 is considered deprecated and will be removed soon. But this means, the bindings-GLFW package from the repository has to be already modified to have `v2-install` working on OpenBSD. Can you apply this patch and add support to bindings-GLFW for OpenBSD? I now use bindings-GLFW v3.3.2.0.
Thank you very much.

**Comment by Mjnd** [comment]
I managed to solve the problem using a local (noindex) repository.
Interestingly, I had to include the package for hsc2hs in the repository, to let it builds bindings-GLFW.
I haven't tested the bindings in my project, but I'm confident they will works.
Regarding the above suggestion, is it feasible?
If not, what is the rationale for not including that harmless (in my opinion) change?
Thank you and sorry for the noise, I should wait and think a little before reporting issues.

**Comment by Mokosha** [comment]
I think having different flavors of linux as part of the conditional for linux is fine. Feel free to submit a patch and I will review it.

**Comment by Mjnd** [comment]
I don't use github so I apologize if I'm wrong.
It seems I need to be added as a collaborator to have permission to start a new branch, for adding the OpenBSD support. Since the diff is trivial, can I just post it here?

    --- .\bindings-GLFW.cabal.orig	2021-06-03 11:23:30.452225800 +0200
    +++ .\bindings-GLFW.cabal	2021-06-03 11:24:24.377400300 +0200
    @@ -133,7 +133,7 @@ library
           glfw/deps/glad_gl.c
           glfw/deps/glad_vulkan.c
 
    -    if os(linux) || os(freebsd)
    +    if os(linux) || os(freebsd) || os(openbsd)
           c-sources:
             glfw/src/glx_context.c
             glfw/src/xkb_unicode.c

I don't want to unneccessarily bother you, but I'm used to the OpenBSD way of doing things (simplest as possible), so this all seems to me unneccessarily complex (I mean the way you have to use github for such trivial matters). If there are issues I don't have considered, feel free to ignore the diff and the conversation, I will continue as I have always done until now, it's not a problem. Thank you anyway.

**Comment by Mjnd** [comment]
The change highlighted above works only with the use of system glfw.
I'm now working on the proper OpenBSD support. Could you add me, in the meantime, to the contributors list, so when the patch will be ready, I'll be able to summit it? Thank you.

**Comment by bsl** [comment]
@Mjnd Hi, thanks for contributing. A cool way to collaborate is for you to clone this repo into your own account, and then make changes against that repo, which you of course have permissions over, and then submit a pull request back to here for the maintainers to review and possibly merge.

**Comment by Mjnd** [comment]
I managed to have the bundled glfw (v3.3.2) compile and work on OpenBSD.
OpenBSD doesn't support `<sys/inotify.h>` so I had to disable the compiling of `linux_joystick.c` (relying on inotify) and replace it with dummy functions, as it was done on previous versions of glfw (the code was hidden behind `#if defined(__linux__)` and `#endif`).

`bindings-GLFW.cabal.diff`

    --- bindings-GLFW.cabal	Fri Feb 21 07:36:07 2020
    +++ bindings-GLFW.cabal	Fri Jun  4 16:21:05 2021
    @@ -133,11 +133,16 @@ library
           glfw/deps/glad_gl.c
           glfw/deps/glad_vulkan.c
 
    -    if os(linux) || os(freebsd)
    +    if os(linux) || os(freebsd) || os(openbsd)
    +      if os(openbsd)
    +        c-sources:
    +          glfw/src/openbsd_joystick.c
    +      else
    +        c-sources:
    +          glfw/src/linux_joystick.c
           c-sources:
             glfw/src/glx_context.c
             glfw/src/xkb_unicode.c
    -        glfw/src/linux_joystick.c
             glfw/src/posix_time.c
             glfw/src/posix_thread.c
           if flag(X)

`openbsd_joystick.c`

    #include "internal.h"

    static void closeJoystick(_GLFWjoystick* js)
    {
        _glfwFreeJoystick(js);
        _glfwInputJoystick(js, GLFW_DISCONNECTED);
    }

    GLFWbool _glfwInitJoysticksLinux(void)
    {
        return GLFW_FALSE;
    }

    void _glfwTerminateJoysticksLinux(void) {}

    void _glfwDetectJoystickConnectionLinux(void) {}

    int _glfwPlatformPollJoystick(_GLFWjoystick* js, int mode)
    {
        return GLFW_FALSE;
    }

    void _glfwPlatformUpdateGamepadGUID(char* guid) {}

If the patch is eligible, as I don't use git/github (except for bothering you), may I ask to relying on you to be committed? I don't want to lose time on a program which I'll use only once, and have to fight with its intricacies... I swear I won't bother you again for at least a year!
If the patch is wrong or not good enough, please tell how it can be improved.
Thank you very much.

**Comment by Mjnd** [comment]
Actually you don't even need my `openbsd_joystick.c`, just copy `null_joystick.c` to `openbsd_joystick.c`.
If you know of a better way to replace `linux_joystick.c` witch the content of `null_joystick.c` when compiling under OpenBSD, please go ahead.

**Comment by Mjnd** [comment]
Here I slightly better diff, which mimics what is done in CMakeLists.txt (not tested, I'm tired of this, but I'm sure it will works):

    --- bindings-GLFW.cabal	Fri Feb 21 07:36:07 2020
    +++ bindings-GLFW.cabal	Sun Jun  6 10:32:40 2021
    @@ -133,11 +133,10 @@ library
           glfw/deps/glad_gl.c
           glfw/deps/glad_vulkan.c
 
    -    if os(linux) || os(freebsd)
    +    if os(linux) || os(freebsd) || os(openbsd)
           c-sources:
             glfw/src/glx_context.c
             glfw/src/xkb_unicode.c
    -        glfw/src/linux_joystick.c
             glfw/src/posix_time.c
             glfw/src/posix_thread.c
           if flag(X)
    @@ -146,12 +145,20 @@ library
               glfw/src/x11_init.c
               glfw/src/x11_monitor.c
               glfw/src/x11_window.c
    +        if os(linux) || os(freebsd)
    +          c-sources: glfw/src/linux_joystick.c
    +        else
    +          c-sources: glfw/src/null_joystick.c
           if flag(Wayland)
             cc-options: -DBINDINGS_GLFW_USE_WAYLAND -D_GLFW_WAYLAND
             c-sources:
               glfw/src/wl_init.c
               glfw/src/wl_monitor.c
               glfw/src/wl_window.c
    +        if os(linux) || os(freebsd)
    +          c-sources: glfw/src/linux_joystick.c
    +        else
    +          c-sources: glfw/src/null_joystick.c
           if flag(OSMesa)
             cc-options: -DBINDINGS_GLFW_USE_OSMESA -D_GLFW_OSMESA
             c-sources:

As the modification is limited to `bindings-GLFW.cabal`, couldn't the hackage revision system be used?
