### ISSUE TITLE
broken on M1 macs

### ISSUE THREAD

**Issue by cvogt** [bsl/bindings-GLFW#74]
environment: M1 mac running Monterey

reproduction steps:
call `GLFW.pollEvents`

expected result:
works as documented

actual result:
`Error'PlatformErrorCocoa: Failed to find service port for display`

cause of the issue:
The latest release 3.3.2.0 of bindings-GLFW uses a version of GLFW that is broken on M1 macs. Updating to a newer GLFW fixes the problem. For example GLFW 3.3.8 used in commit f41829415c2079318eaf6893473c26efebddf127 of https://github.com/TristanCacqueray/bindings-GLFW.git does not show this issue and works as expected.

**Comment by cvogt** [comment]
I just tried it, this PR also fixes the issue: https://github.com/bsl/bindings-GLFW/pull/73

**Comment by bsl** [comment]
Hi, thank you for figuring this out. I hope we can get a release out for you. The problem is that I am approximately one million years old, and turned into a Buddhist monk. Do we have any energetic contributors who can actually push a release to... whatever the current Haskell package thing is?
