### ISSUE TITLE
Unknown Symbol `__objc_empty_vtable` OS X 10.9

### ISSUE THREAD

**Issue by MaxDaten** [bsl/bindings-GLFW#8]
Sorry for creating this issue, but I need a place to publicly trac my current informations about this issue.

On a 10.8 -> 10.9 updated OS X building and linking `bindings-GLFW` runs in the following error:
```
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package bindings-DSL-1.0.20 ... linking ... done.
Loading package bindings-GLFW-3.0.3 ... linking ... ghc:
lookupSymbol failed in relocateSection (relocate external)
/Users/jloos/Workspace/hs/bindings-GLFW/dist/build/HSbindings-GLFW-3.0.3.o: unknown symbol `__objc_empty_vtable'
ghc: unable to load package `bindings-GLFW-3.0.3'
```

`__objc_empty_vtable` is part of the Objective-C runtime.
This error is already mentioned in bsl/bindings-GLFW/issues/5 https://github.com/bsl/bindings-GLFW/issues/5#issuecomment-26884065

It happens with the apple-gcc-4.2.1 and homebrew'ed gcc48

Maybe it is in a way related to the libc++ libstdc++ changes in 10.9 (despite the ObjC relation?) reported in https://github.com/mxcl/homebrew/issues/23687 or maybe completely an ghc-7.6.3 linking issue. Linking will be improved in ghc 7.8, I tried the ghc HEAD and linking to `bindings-GLFW` works, but ghc 7.8 runs a way better with clang at all, maybe 'just' a side effect.

After some further investigation, I will report this issue on the ghc trac.

@bsl dont bother yourself with this issue to much, it's more ore less just for me and more an investigation tracing.

**Comment by schell** [comment]
We're now far into 7.8.3 and I haven't run into any of these problems since, so I'm closing this out. Feel free to reopen.
